### ISSUE TITLE
return a 502 error?

### ISSUE THREAD

**Issue by xhemj** [adityatelange/gourl#2]
After I deployed it according to your deployment method, why did it return a 502 error?
![image](https://user-images.githubusercontent.com/55266496/93666985-1bc2d780-fab5-11ea-8e12-e568f6876a8f.png)

**Comment by adityatelange** [comment]
Please **check the logs** . It may show you what went wrong 

Hope you have added variable as shown below
![image](https://user-images.githubusercontent.com/21258296/93668831-f205b280-faac-11ea-88d4-a9575cfd755d.png)

I have updated README in case if it was creating confusion https://github.com/adityatelange/gourl#how-to-deploy

**Comment by xhemj** [comment]
Oh, thanks
